#!/usr/bin/env python3
"""Generate Codex skills and the self-contained cross-harness plugin bundle.

.claude/skills/ is the source of truth. Everything in .agents/skills/ is
generated by this script and must not be edited by hand. The plugin's Claude
and Codex skill trees are generated mirrors so marketplace installs never need
to reach outside the plugin directory.

    python3 scripts/port-to-codex.py            write the port
    python3 scripts/port-to-codex.py --check    fail if the port is stale

The transformations are exactly the harness-specific mechanics listed in
README.md's "Harnesses" table. If a skill needs something that is not in the
map below, that is a harness difference nobody has named yet - name it here,
not by editing the generated file.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / ".claude" / "skills"
DST = ROOT / ".agents" / "skills"
CLAUDE_PLUGIN_DST = ROOT / "plugins" / "claude" / "kaitersberg" / "skills"
CODEX_PLUGIN_DST = ROOT / "plugins" / "codex" / "kaitersberg" / "skills"
VERBATIM_ASSET_SUFFIXES = {".json"}

# Frontmatter keys: kept, and dropped because Codex has no equivalent.
KEEP = {"name", "description"}
DROP = {"argument-hint", "user-invocable", "allowed-tools", "model",
        "disable-model-invocation"}

BANNER = (
    "<!-- Generated from .claude/skills/{name}/ by scripts/port-to-codex.py.\n"
    "     Do not edit: edit the source and regenerate. -->\n"
)

CODEX_BROWSER = """Use the Codex Browser plugin (`@Browser`) for this phase. For a local web
application, open its local URL in the built-in browser. Enable Browser Developer
mode with full CDP access when console, network, DOM or style inspection is required.

Before testing:

- Confirm that Browser is available and can open the application. The built-in
  browser is available in the ChatGPT desktop app, not Codex CLI or the IDE extension.
- If Browser is unavailable, do not claim the walkthrough passed and do not replace
  it with an assertion from screenshots alone. Mark every affected criterion
  `blocked`, state that browser automation was unavailable, and continue only with
  criteria that can be verified outside the browser.
- Use a fresh browser tab and Browser's isolated profile. Do not reuse unrelated
  user tabs or authenticated sessions.

Then:"""

# Prose replacements, applied in order. Plain strings, not regexes.
PROSE = [
    ("CLAUDE.md", "AGENTS.md"),
    (".claude/skills/", ".agents/skills/"),
    ("AskUserQuestion", "a multiple-choice question"),
    # Longest first: a bare token swap would leave "Invoke the `the harness's ...` skill".
    (
        "Invoke the `claude-in-chrome` skill before using any browser tool. Then:",
        CODEX_BROWSER,
    ),
    (
        "**Read the console and failed network requests** after each meaningful step\n"
        "  (`read_console_messages` and the browser's network inspection) - a feature that\n"
        "  works while throwing errors, unhandled rejections or unexpected failed requests\n"
        "  is not passing.",
        "**Inspect the console and failed network requests** after each meaningful step\n"
        "  with Browser Developer mode/CDP - a feature that works while throwing errors,\n"
        "  unhandled rejections or unexpected failed requests is not passing.",
    ),
    (
        "- Open a new tab; do not hijack the user's tabs.",
        "- Open the application in that fresh tab.",
    ),
    (
        "- Do not click anything that raises a browser dialog - it will freeze the session.",
        "- Do not bypass browser permission or confirmation prompts. If a required action\n"
        "  cannot be automated, including a file upload, mark that step `blocked` and\n"
        "  record why.",
    ),
    ("Claude in Chrome", "Codex Browser"),
    ("claude-in-chrome", "Codex Browser"),
]


def transform(text: str, name: str, skills: list[str], is_skill_file: bool) -> str:
    if is_skill_file:
        _, fm, body = text.split("---\n", 2)
        kept, seen = [], set()
        for line in fm.splitlines():
            key = line.split(":", 1)[0].strip()
            seen.add(key)
            if key in KEEP:
                kept.append(line)
            elif key not in DROP:
                sys.exit(f"{name}: unknown frontmatter key {key!r} - decide in {Path(__file__).name} whether Codex keeps it")
        missing = KEEP - seen
        if missing:
            sys.exit(f"{name}: frontmatter is missing {sorted(missing)}")
        text = "---\n" + "\n".join(kept) + "\n---\n" + body

    # /skill-name -> $skill-name, only where it is an invocation: at the start of a
    # line or after a space, a backtick or an opening bracket. Never inside a path
    # like docs/architecture.md or features/PROJ-x-<name>/qa.md.
    text = re.sub(
        r"(?:(?<=^)|(?<=[\s`(\[]))/(" + "|".join(skills) + r")\b",
        r"$\1",
        text,
        flags=re.MULTILINE,
    )
    for a, b in PROSE:
        text = text.replace(a, b)

    # Claude context files support line-level @path imports. Codex AGENTS.md does
    # not. Templates must use a plain reading list that works in both harnesses;
    # fail if a future source template reintroduces silent no-op syntax.
    # a bare @path line: needs a slash or an .md tail, so indented CSS at-rules
    # (@media, @keyframes) in the /status template are not false positives
    if re.search(r"(?m)^[ \t]*@(?:[\w.-]+/|[\w-]+\.md\b)", text):
        sys.exit(
            f"{name}: Claude-style @path import remains in the Codex port - "
            "replace it with an explicit reading instruction in the source template"
        )

    if is_skill_file:  # after the replacements, so the banner keeps its own paths
        head, body = text.split("---\n", 2)[1:]
        text = "---\n" + head + "---\n" + BANNER.format(name=name) + body
    return text


def main() -> int:
    check = "--check" in sys.argv
    skills = sorted(p.name for p in SRC.iterdir() if p.is_dir())
    stale = []

    for name in skills:
        others = [
            p for p in (SRC / name).rglob("*")
            if p.is_file() and p.suffix not in VERBATIM_ASSET_SUFFIXES | {".md"}
        ]
        if others:
            sys.exit(f"{name}: the skill has unsupported assets "
                     + ", ".join(p.name for p in others) + " - decide here how those port")
        for src in sorted(p for p in (SRC / name).rglob("*") if p.is_file()):
            rel = src.relative_to(SRC)
            source = src.read_bytes()
            if src.suffix == ".md":
                source_text = source.decode()
                codex = transform(
                    source_text, name, skills, src.name == "SKILL.md"
                ).encode()
            else:
                # Data templates have no harness syntax. Copy them byte-for-byte
                # so a skill can point at a machine-readable output contract.
                codex = source
            outputs = (
                (DST / rel, codex),
                (CLAUDE_PLUGIN_DST / rel, source),
                (CODEX_PLUGIN_DST / rel, codex),
            )
            for dst, output in outputs:
                if check:
                    if not dst.exists() or dst.read_bytes() != output:
                        stale.append(str(dst.relative_to(ROOT)))
                else:
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    dst.write_bytes(output)

    destinations = (DST, CLAUDE_PLUGIN_DST, CODEX_PLUGIN_DST)
    extra = [
        str(path.relative_to(ROOT))
        for destination in destinations
        if destination.exists()
        for path in destination.iterdir()
        if path.is_dir() and path.name not in skills
    ]

    if check:
        for rel in stale:
            print(f"stale: {rel}")
        for path in extra:
            print(f"orphan: {path} has no source skill")
        if stale or extra:
            print("\nRun: python3 scripts/port-to-codex.py")
            return 1
        print(f"Codex port and plugin bundle are in step with all {len(skills)} skills.")
        return 0

    for path in extra:
        print(f"orphan (left alone): {path} has no source skill")
    print(f"Ported {len(skills)} skills to .agents/skills/ and the plugin bundle")
    return 0


if __name__ == "__main__":
    sys.exit(main())
